[package]
name = "waka-tray"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
core-foundation = "0.10.0"
image = "0.25.2"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = "1.0.210"
tao = "0.30.0"
tokio = "1.40.0"
tray-icon = "0.17.0"
